# Generated by Django 5.2 on 2025-08-12 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('Student_id', models.CharField(max_length=100, unique=True)),
                ('fees_date', models.DateField()),
                ('course_name', models.CharField(choices=[('python', 'Python Full Stack '), ('wd', 'Web Development'), ('olevel', 'O Level'), ('adca', 'ADCA'), ('dca', 'DCA')], max_length=50)),
                ('course_fees', models.CharField()),
                ('installment_no', models.CharField(max_length=12)),
                ('student_img', models.ImageField(upload_to='student_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveIntegerField()),
                ('fees_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='fees.student')),
            ],
        ),
    ]
