# Generated by Django 5.2.1 on 2025-09-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_name',
            field=models.CharField(choices=[('python', 'Python Full Stack '), ('wd', 'Web Development'), ('olevel', 'O Level'), ('adca', 'ADCA'), ('DCA', 'DCA'), ('DTP', 'DTP'), ('DCFA', 'DCFA'), ('CCC', 'CCC'), ('EXCEL', 'EXCEL'), ('TALLY', 'TALLY'), ('WORD', 'WORD'), ('TYPING', 'TYPING')], max_length=50),
        ),
    ]
