# Generated by Django 5.2.1 on 2025-09-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_student_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_name',
            field=models.CharField(choices=[('python', 'Python Full Stack '), ('wd', 'Web Development'), ('olevel', 'O Level'), ('adca', 'ADCA'), ('dca', 'dca'), ('dtp', 'dtp'), ('dcfa', 'dcfa'), ('ccc', 'ccc'), ('excel', 'excel'), ('tally', 'tally'), ('word', 'word'), ('typing', 'typing')], max_length=50),
        ),
    ]
