# Generated by Django 5.2.1 on 2026-05-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_student_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_name',
            field=models.CharField(choices=[('python', 'Python Full Stack '), ('wd', 'Web Development'), ('olevel', 'O Level'), ('adca', 'ADCA'), ('dca', 'dca'), ('dtp', 'DTP'), ('dcfa', 'dcfa'), ('ccc', 'ccc'), ('excel', 'excel'), ('tally', 'tally'), ('word', 'word'), ('typing', 'typing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_img',
            field=models.ImageField(blank=True, null=True, upload_to='student_photo/'),
        ),
    ]
